// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx5ujSVWqTqNGQYxnIBKA5wsX-MQa9DXs',
    appId: '1:6196449018:web:67ab6c51ccc7161a1ac343',
    messagingSenderId: '6196449018',
    projectId: 'tripaz-travel-app',
    authDomain: 'tripaz-travel-app.firebaseapp.com',
    storageBucket: 'tripaz-travel-app.appspot.com',
    measurementId: 'G-MLTQNG132R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9K9V7xLV8Dfwnd6xmydL_fw7uQzMpJWo',
    appId: '1:6196449018:android:ad7b3b8e5be7ed431ac343',
    messagingSenderId: '6196449018',
    projectId: 'tripaz-travel-app',
    storageBucket: 'tripaz-travel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA66TPz6UMHrVqiAHFAxrcORLKBGBDiNI',
    appId: '1:6196449018:ios:5a321498c3cb31391ac343',
    messagingSenderId: '6196449018',
    projectId: 'tripaz-travel-app',
    storageBucket: 'tripaz-travel-app.appspot.com',
    iosBundleId: 'com.hasanshukurov.sanTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA66TPz6UMHrVqiAHFAxrcORLKBGBDiNI',
    appId: '1:6196449018:ios:5a321498c3cb31391ac343',
    messagingSenderId: '6196449018',
    projectId: 'tripaz-travel-app',
    storageBucket: 'tripaz-travel-app.appspot.com',
    iosBundleId: 'com.hasanshukurov.sanTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx5ujSVWqTqNGQYxnIBKA5wsX-MQa9DXs',
    appId: '1:6196449018:web:e0d0d9a667671e031ac343',
    messagingSenderId: '6196449018',
    projectId: 'tripaz-travel-app',
    authDomain: 'tripaz-travel-app.firebaseapp.com',
    storageBucket: 'tripaz-travel-app.appspot.com',
    measurementId: 'G-6LREND5L58',
  );
}
